export type AtsType =
  | "greenhouse"
  | "lever"
  | "ashby"
  | "workable"
  | "smartrecruiters"
  | "workday"
  | "custom_json"
  | "custom_scraper";

export type CompanyConfig = {
  name: string;
  ats: AtsType;
  slug: string;
  tenant?: string;
  notes?: string;
};

export const COMPANIES: CompanyConfig[] = [
  { name: "Stripe", ats: "greenhouse", slug: "stripe" },
  { name: "Airbnb", ats: "greenhouse", slug: "airbnb" },
  { name: "Coinbase", ats: "greenhouse", slug: "coinbase" },
  { name: "Databricks", ats: "greenhouse", slug: "databricks" },
  { name: "Snowflake", ats: "greenhouse", slug: "snowflake" },
  { name: "Figma", ats: "greenhouse", slug: "figma" },
  { name: "Notion", ats: "greenhouse", slug: "notion" },
  { name: "Ramp", ats: "greenhouse", slug: "ramp" },
  { name: "Atlassian", ats: "greenhouse", slug: "atlassian" },
  { name: "Cloudflare", ats: "greenhouse", slug: "cloudflare" },
  { name: "GitLab", ats: "greenhouse", slug: "gitlab" },
  { name: "HashiCorp", ats: "greenhouse", slug: "hashicorp" },
  { name: "MongoDB", ats: "greenhouse", slug: "mongodb" },
  { name: "DoorDash", ats: "greenhouse", slug: "doordash" },
  { name: "Plaid", ats: "greenhouse", slug: "plaid" },
  { name: "Robinhood", ats: "greenhouse", slug: "robinhood" },
  { name: "Discord", ats: "greenhouse", slug: "discord" },
  { name: "Reddit", ats: "greenhouse", slug: "reddit" },
  { name: "Rippling", ats: "greenhouse", slug: "rippling" },
  { name: "Brex", ats: "greenhouse", slug: "brex" },
  { name: "Postman", ats: "greenhouse", slug: "postman" },
  { name: "Confluent", ats: "greenhouse", slug: "confluent" },
  { name: "Datadog", ats: "greenhouse", slug: "datadog" },
  { name: "Shopify", ats: "greenhouse", slug: "shopify" },
  { name: "Pinterest", ats: "greenhouse", slug: "pinterest" },
  { name: "Dropbox", ats: "greenhouse", slug: "dropbox" },
  { name: "Lyft", ats: "greenhouse", slug: "lyft" },
  { name: "Instacart", ats: "greenhouse", slug: "instacart" },
  { name: "Asana", ats: "greenhouse", slug: "asana" },
  { name: "Okta", ats: "greenhouse", slug: "okta" },
  { name: "PagerDuty", ats: "greenhouse", slug: "pagerduty" },
  { name: "1Password", ats: "greenhouse", slug: "1password" },
  { name: "Canva", ats: "greenhouse", slug: "canva" },
  { name: "Miro", ats: "greenhouse", slug: "miro" },
  { name: "Airtable", ats: "greenhouse", slug: "airtable" },
  { name: "Webflow", ats: "greenhouse", slug: "webflow" },
  { name: "Zapier", ats: "greenhouse", slug: "zapier" },
  { name: "Affirm", ats: "greenhouse", slug: "affirm" },
  { name: "Anthropic", ats: "greenhouse", slug: "anthropic" },
  { name: "CrowdStrike", ats: "greenhouse", slug: "crowdstrike" },
  { name: "LaunchDarkly", ats: "greenhouse", slug: "launchdarkly" },
  { name: "Sentry", ats: "greenhouse", slug: "sentry" },
  { name: "Temporal", ats: "greenhouse", slug: "temporal" },
  { name: "PlanetScale", ats: "greenhouse", slug: "planetscale" },
  { name: "Supabase", ats: "greenhouse", slug: "supabase" },
  { name: "Scale AI", ats: "greenhouse", slug: "scaleai" },
  { name: "Hugging Face", ats: "greenhouse", slug: "huggingface" },
  { name: "Together AI", ats: "greenhouse", slug: "togetherai" },
  { name: "Fireworks AI", ats: "greenhouse", slug: "fireworksai" },
  { name: "Docker", ats: "greenhouse", slug: "docker" },
  { name: "Algolia", ats: "greenhouse", slug: "algolia" },
  { name: "Netlify", ats: "greenhouse", slug: "netlify" },
  { name: "Twilio", ats: "greenhouse", slug: "twilio" },
  { name: "Cohere", ats: "greenhouse", slug: "cohere" },
  { name: "Mistral AI", ats: "greenhouse", slug: "mistral" },
  { name: "Weights & Biases", ats: "greenhouse", slug: "wandb" },
  { name: "Glean", ats: "greenhouse", slug: "glean" },
  { name: "ElevenLabs", ats: "greenhouse", slug: "elevenlabs" },
  { name: "Harvey", ats: "greenhouse", slug: "harvey" },
  { name: "Writer", ats: "greenhouse", slug: "writer" },
  { name: "UiPath", ats: "greenhouse", slug: "uipath" },
  { name: "Nutanix", ats: "greenhouse", slug: "nutanix" },
  { name: "Rubrik", ats: "greenhouse", slug: "rubrik" },
  { name: "Druva", ats: "greenhouse", slug: "druva" },
  { name: "Celonis", ats: "greenhouse", slug: "celonis" },
  { name: "Wise", ats: "greenhouse", slug: "wise" },
  { name: "Mercury", ats: "greenhouse", slug: "mercury" },
  { name: "Harness", ats: "greenhouse", slug: "harness" },
  { name: "Coda", ats: "greenhouse", slug: "coda" },

  { name: "Elastic", ats: "lever", slug: "elastic" },
  { name: "Mixpanel", ats: "lever", slug: "mixpanel" },
  { name: "BrowserStack", ats: "lever", slug: "browserstack" },
  { name: "Groww", ats: "lever", slug: "groww" },
  { name: "Freshworks", ats: "lever", slug: "freshworks" },
  { name: "Zepto", ats: "lever", slug: "zepto" },
  { name: "Dream11", ats: "lever", slug: "dream11" },
  { name: "MPL", ats: "lever", slug: "mpl" },
  { name: "CRED", ats: "lever", slug: "cred" },
  { name: "Razorpay", ats: "lever", slug: "razorpay" },

  { name: "Perplexity", ats: "ashby", slug: "perplexity" },
  { name: "Linear", ats: "ashby", slug: "linear" },
  { name: "Vercel", ats: "ashby", slug: "vercel" },
  { name: "Retool", ats: "ashby", slug: "retool" },
  { name: "Replit", ats: "ashby", slug: "replit" },
  { name: "Statsig", ats: "ashby", slug: "statsig" },
  { name: "OpenAI", ats: "ashby", slug: "openai" },
  { name: "Character AI", ats: "ashby", slug: "character" },
  { name: "Runway", ats: "ashby", slug: "runwayml" },
  { name: "LangChain", ats: "ashby", slug: "langchain" },
  { name: "Pinecone", ats: "ashby", slug: "pinecone" },
  { name: "Anyscale", ats: "ashby", slug: "anyscale" },
  { name: "Cursor", ats: "ashby", slug: "anysphere" },

  // Workday tenants — pending workday.ts adapter implementation
  { name: "Adobe", ats: "workday", slug: "adobe", tenant: "adobe" },
  { name: "Oracle", ats: "workday", slug: "oracle", tenant: "oracle" },
  { name: "Salesforce", ats: "workday", slug: "salesforce", tenant: "salesforce" },
  { name: "Walmart", ats: "workday", slug: "walmart", tenant: "walmart" },
  { name: "Nvidia", ats: "workday", slug: "nvidia", tenant: "nvidia" },
  { name: "Qualcomm", ats: "workday", slug: "qualcomm", tenant: "qualcomm" },
  { name: "Mastercard", ats: "workday", slug: "mastercard", tenant: "mastercard" },
  { name: "Visa", ats: "workday", slug: "visa", tenant: "visa" },
  { name: "PayPal", ats: "workday", slug: "paypal", tenant: "paypal" },
  { name: "Block", ats: "workday", slug: "block", tenant: "square" },
  { name: "Cisco", ats: "workday", slug: "cisco", tenant: "cisco" },
  { name: "SAP", ats: "workday", slug: "sap", tenant: "sap" },
  { name: "Intel", ats: "workday", slug: "intel", tenant: "intel" },
  { name: "Dell", ats: "workday", slug: "dell", tenant: "dell" },

  // Custom JSON — pending per-company adapters
  { name: "Amazon", ats: "custom_json", slug: "amazon" },
  { name: "Google", ats: "custom_json", slug: "google" },
  { name: "Microsoft", ats: "custom_json", slug: "microsoft" },
  { name: "Apple", ats: "custom_json", slug: "apple" },
  { name: "Uber", ats: "custom_json", slug: "uber" },
  { name: "IBM", ats: "custom_json", slug: "ibm" },
  { name: "ServiceNow", ats: "custom_json", slug: "servicenow" },
  { name: "Samsung R&D", ats: "custom_json", slug: "samsung_rd" },

  // Indian custom portals — pending per-company scrapers
  { name: "Flipkart", ats: "custom_scraper", slug: "flipkart" },
  { name: "Myntra", ats: "custom_scraper", slug: "myntra" },
  { name: "Swiggy", ats: "custom_scraper", slug: "swiggy" },
  { name: "Zomato", ats: "custom_scraper", slug: "zomato" },
  { name: "Paytm", ats: "custom_scraper", slug: "paytm" },
  { name: "PhonePe", ats: "custom_scraper", slug: "phonepe" },
  { name: "Juspay", ats: "custom_scraper", slug: "juspay" },
  { name: "Meesho", ats: "custom_scraper", slug: "meesho" },
  { name: "Zerodha", ats: "custom_scraper", slug: "zerodha" },
  { name: "Ola", ats: "custom_scraper", slug: "ola" },
  { name: "Unacademy", ats: "custom_scraper", slug: "unacademy" },
  { name: "Sarvam AI", ats: "custom_scraper", slug: "sarvam" },
  { name: "Krutrim", ats: "custom_scraper", slug: "krutrim" },
  { name: "Ola Krutrim", ats: "custom_scraper", slug: "ola_krutrim" },
];

export const BY_ATS = {
  greenhouse: COMPANIES.filter((c) => c.ats === "greenhouse"),
  lever: COMPANIES.filter((c) => c.ats === "lever"),
  ashby: COMPANIES.filter((c) => c.ats === "ashby"),
  workable: COMPANIES.filter((c) => c.ats === "workable"),
  smartrecruiters: COMPANIES.filter((c) => c.ats === "smartrecruiters"),
  workday: COMPANIES.filter((c) => c.ats === "workday"),
  custom_json: COMPANIES.filter((c) => c.ats === "custom_json"),
  custom_scraper: COMPANIES.filter((c) => c.ats === "custom_scraper"),
};
